# Generated by Django 5.1.2 on 2024-10-22 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BankLoanDB',
            fields=[
                ('name', models.CharField(max_length=20)),
                ('loanID', models.IntegerField(primary_key='loanID', serialize=False)),
                ('accno', models.IntegerField()),
                ('occupation', models.CharField(max_length=20)),
                ('collateral', models.CharField(max_length=40)),
            ],
        ),
    ]
